### ISSUE TITLE
.net core version 3.10 not found.

### ISSUE THREAD

**Issue by bhaweshksingh** [bimspot/xeokit-converter#3] opened 2020-09-12 10:34 UTC
root@8bbb7762514a:/# xeokit-metadata scene.ifc scene.json
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.2.8 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by eriadam** [comment] 2020-09-16 17:49
Duplicate of #4 .

**Closed as completed by eriadam** 2020-09-16 17:49 UTC
